aesara-devs/aemcmc

aemcmc/dists.py, aemcmc/negative_binomial_horseshoe_gibbs.py, requirements.txt, tests/test_dists.py, tests/test_horseshoe_nbinom_gibbs.py
This PR adds functions for creating sampler steps for a normal regression under a Horseshoe prior as described in  "A Simple Sampler for the Horseshoe Estimator" (Makalic, Enes & Schmidt, Daniel, 2015).  
It also implements the Polya-gamma normal scale mixture expansion described in "Data Augmentation for Non-Gaussian Regression Models Using Variance-Mean Mixtures" (Polson, Nicholas G., and James G. Scott, 2013) and the multivariate normal sampler in "Fast Simulation of Hyperplane-Truncated Multivariate Normal Distributions" (Cong, Yulai, Bo Chen, and Mingyuan Zhou, 2017).
=> Add a Gibbs sampler for the Horseshoe prior and a Polya-gamma normal scale-mixture expansion

aemcmc/negative_binomial_horseshoe_gibbs.py
In this PR I add some documentation to the existing gibbs samplers, and minor simplifications to the API.
=> Document the Negative binomial gibbs sampler

.pre-commit-config.yaml
The pre-commit style checks currently fail because of a probleme with
the `click` dependency:  https://github.com/psf/black/issues/2964. The
recommended solution is to upgrade `black` to v22.3.0, which we do in
this commit..
=> Bump black version to 22.3.0 in pre-commit

.github/workflows/test.yml
Python 3.6's support stopped [3 months ago](https://endoflife.date/python) so I don't think we should support it. Python 3.10 was released 6 months ago and we should make sure `aemcmc` is compatible. This closes #20.
=> Remove Python 3.6 and add 3.10 to CI test matrix

aemcmc/gibbs.py, tests/test_gibbs.py
The samplers currently assume that there is an intercept term in the
regressions, and this term is treated separately from the other
regression parameters (Makalic & Schmidt 2016). This is limiting for two
reasons:
1. We don't always want to run regressions with an intercept parameter;
at the very least we'd like to control its prior value.
2. This complicates the work for #16.
In this commit we generalize the Gibbs samplers by removing
the separation between the intercept beta0 and the other regression parameters.
Closes #17 
@brandonwillard Many references mention having a separate prior for the intercept parameter, which does make sense. Are there cases that you know of where adding a shrinkage prior to the intercept changes the results? 
Also I've noticed we don't have any tests to …
=> Remove the intercept assumption in Gibbs samplers

tests/test_dists.py
The tests for the distribution rely on a specific random number generator implementation and seed. These tests broke as the result of a change upstream in aesara 2.6.5 (I suspect the change happened here https://github.com/aesara-devs/aesara/pull/939). This should not happen and we thus need better tests for the distributions.
=> Fix flaky tests

aemcmc/gibbs.py, tests/test_gibbs.py
This PR will be adding Gibbs steps that would allow sampling for dispersion terms of Negative Binomial. 
This PR will follow the compound poisson method mentioned [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4180062/)
So far we roughy added the Gibbs steps for  
1. r -dispersion terms in N(r, p)
2. h - Inverse of scale parameter for gamma distribution of r
3. L_i - The number terms of L/N of a Poisson distributed variable in Compound Poisson distribution
The most tricky part so far comes form the sampling of L_i as it is a discrete sampling from a given probability vector where the probability vector comes from a pre-calculated matrix with some additional computation. 
Next step is to add `match` functions for the NB graph with dispersion terms.
=> Add a Gibbs sampler for the negative-binomial dispersion parameter

aemcmc/utils.py, tests/test_utils.py
We currently have to pass respectively an empty tuple and an empty dictionary to initialize `ModelInfo` when we do not wish to sample from deterministic variables and/or when the model does not produce updates. This PR makes the specification of `deterministic_vars` and `updates` optional.  
`rvs_to_values` and `observed_rvs` are now the only compulsory fields.
Closes #40
=> Make `deterministic_vars` and `updates` optional in `ModelInfo`

aemcmc/transforms.py, tests/test_conjugates.py, tests/test_transforms.py
In this PR we add a relation that represents loc-scale transformations (the relation between the "centered" and "non-centered" parametrization). The performance of some sampling algorithms (eg HMC) can be affected by the parametrization of the model provided by the user (see [this example](https://pymc-devs.github.io/symbolic-pymc/theano-radon-example.html)). 
We would like `aemcmc` to be aware of the different parametrizations so [users don't have to](https://arxiv.org/abs/1906.03028
) worry of these implementation details.
I see that [the Symbolic-PyMC implementation](https://github.com/pymc-devs/symbolic-pymc/blob/84e8d612c714f502f8d188c1766498f4ff7beecf/symbolic_pymc/relations/theano/distributions.py#L112) excludes the cases where `loc=0` and `sd=1` but I am not sure that it is …
=> Add relation for recentering and rescaling

aemcmc/dists.py, tests/test_dists.py
This commit fixes/completes/extends previously minimal unittests for
some of the available probability distribution samplers, which include:
- `multivariate_normal_cong2017`
- `multivariate_normal_bhattacharya2016`.
This is a followup of https://github.com/aesara-devs/aemcmc/pull/32 and closes #33
=> Extend unittests for some distributions.

aemcmc/ffbs.py, conftest.py, tests/test_ffbs.py
This PR closes #6 by adding an FFBS sampler that takes the initial state probabilities, transition matrices (they can change over the sequence index), and log-probabilities/likelihoods.  It doesn't perform its computations in log-space, in order to avoid the cost; instead, it re-normalizes its forward probabilities according to a numerical "near-zero" bound.
=> Add a forward-filter backward-sampler

aemcmc/nuts.py, setup.py, tests/test_nuts.py
In this PR we add a function that uses the NUTS kernel implemented in `aehmc` to build a function that samples from the posterior distribution of a model specified in a `ModelInfo` instance. It is a first step towards the general-purpose sampler mentioned in #26.
=> Add the NUTS sampler constructor

aemcmc/rewriting.py, environment.yml, setup.py
This PR updates the now deprecated `ShapeFeature` imports (i.e. Aesara >= 2.8.3).
=> Update `ShapeFeature` imports

aemcmc/transforms.py, tests/test_transforms.py
Moves us closer to being able to rewrite the Gibbs sampler for the Horseshoe prior #64. Once this PR and #66 are merged it will be a good time to cross the finish line with  https://github.com/aesara-devs/aesara/pull/1036 and refactor the library so relations work both ways #43 before going into automatic rewrites.
=> Add the transformation between the inverse gamma and the exponential distributions

aemcmc/basic.py, aemcmc/nuts.py, tests/test_basic.py, tests/test_nuts.py
In this PR we assign the NUTS sampler to the variables that have not been assigned a sampler in `construct_sampler`.
_More details to come_
Closes #47
=> Sample remaining variables with the NUTS sampler

aemcmc/__init__.py
=> Make `construct_sampler` available in the `aemcmc` namespace

.pre-commit-config.yaml
The pre-commit checks are currently failing on `main` due to a `mypy` dependency. I updated all the versions to match those in Aesara's `.pre-commit-config.yml`.
=> Update `pre-commit`, `black`, `flake8`, `isort`, `mypy` versions in pre-commit hooks

aemcmc/basic.py, aemcmc/nuts.py, environment.yml, setup.py, tests/test_basic.py, tests/test_nuts.py
AePPL's `joint_logprob` now create the initial values for the sampled RV *in the transformed space*:
```python
logprob, initial_values = joint_logprob(
to_sample_rvs,
realized=realized_rvs_to_values,
transforms=...
)
```
The change to the NUTS constructor itself was very minimal, if anything it simplified it a little (changes are mostly refactoring + better documentation).
We can now build NUTS sampling steps using:
```python
from aemcmc.nuts import construct_nuts_sampler
import aesara.tensor as at
srng = at.random.RandomStream(0)
mu_rv = srng.normal(0, 1, name="mu")
sigma_rv = srng.halfnormal(0.0, 1.0, name="sigma")
Y_rv = srng.normal(mu_rv, sigma_rv, name="Y")
mu_vv = mu_rv.clone()
sigma_vv = sigma_rv.clone()
y_vv = Y_rv.clone()
to_sample_rvs = {mu_rv: mu_vv, sigma_rv: sigma_vv} …
```
=> Update NUTS to work with AePPL's new `joint_logprob` interface

aemcmc/basic.py, aemcmc/rewriting.py, tests/test_rewriting.py
This fixes the error seen in #90.  
The underlying issue is that `SubsumingElemwise` extends `OpFromGraph` and the latter does not accept constant inputs (e.g. an `OpFromGraph` representing `1 / x` should only take `x` as an input, and not also `1`).  This PR removes constant inputs when the `OpFromGraph` is constructed and also strips them from calls to `SubsumingElemwise.make_node`.  The assumption is that the inputs provided in both cases (i.e. when the `Op` is constructed and when the constructed `Op` is used to create a node) refer to the same constants, which they absolutely should in this scenario.
=> Fix handling of constant inputs to `SubsumingElemwise`

.github/workflows/test.yml, .github/workflows/update-pre-commit.yml, .pre-commit-config.yaml, .readthedocs.yml, Makefile, aemcmc/basic.py, aemcmc/conjugates.py, aemcmc/gibbs.py, aemcmc/nuts.py, aemcmc/rewriting.py, aemcmc/types.py, aemcmc/utils.py, setup.py, tests/test_basic.py, tests/test_gibbs.py, tests/test_transforms.py
This PR updates the CI setup to better reflect Aesara's setup.  It also removes explicit support for Python 3.7.
=> Update CI setup and remove Python 3.7
